---
- name: Create directory for installed apps
  file:
    path: "{{ lookup('env','HOME') }}/Applications"
    state: directory
    mode: 0775
  tags:
    - caskapps

- name: install cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=$HOME/Applications/"
  with_items:
    - "slack"
    - "visual-studio-code"
    - "postman"
    - "github"
    - "brave-browser"
    - "spotify"
    - "dbvisualizer"
    - "spectacle"
    - "alfred"
    - "caffeine"
    - "iterm2"
    - "bitwarden"
  tags:
    - caskapps

- name: install VSCode packages
  shell: "code --install-extension {{ item }}"
  with_items:
    - "apollographql.vscode-apollo"
    - "broadinstitute.wdl"
    - "broadinstitute.wdl-devtools"
    - "christian-kohler.npm-intellisense"
    - "christian-kohler.path-intellisense"
    - "CoenraadS.bracket-pair-colorizer"
    - "dbaeumer.vscode-eslint"
    - "donjayamanne.githistory"
    - "dzannotti.vscode-babel-coloring"
    - "eamodio.gitlens"
    - "EditorConfig.EditorConfig"
    - "eg2.vscode-npm-script"
    - "esbenp.prettier-vscode"
    - "flowtype.flow-for-vscode"
    - "formulahendry.auto-close-tag"
    - "formulahendry.auto-rename-tag"
    - "formulahendry.code-runner"
    - "golang.go"
    - "himanoa.Python-autopep8"
    - "jansenfuller.crayon-vscode"
    - "KnisterPeter.vscode-github"
    - "LaurentTreguier.vscode-simple-icons"
    - "mgmcdermott.vscode-language-babel"
    - "ms-python.python"
    - "ms-toolsai.jupyter"
    - "msjsdiag.debugger-for-chrome"
    - "pflannery.vscode-versionlens"
    - "PKief.material-icon-theme"
    - "sabeshbharathi.steampunk"
    - "sleistner.vscode-fileutils"
    - "streetsidesoftware.code-spell-checker"
    - "tht13.rst-vscode"
    - "vscode-icons-team.vscode-icons"
  tags:
    - caskapps
